### ISSUE TITLE
Market Open Time

### ISSUE THREAD

**Issue by ericraio** [earlonrails/alpaca-go-heroku#1]
First of all, great little script. I forked it and had fun writing with it.

Your screenshot shows 2:30 UTC which translates to 10:30 eastern time, shouldn't it be 1:30 UTC or 1:00 ?

**Comment by earlonrails** [comment]
Hey thanks for that! Sorry I didn't see this sooner yes it should be 1:30 UTC I will update

**Comment by earlonrails** [comment]
https://github.com/earlonrails/alpaca-go-heroku/pull/2

Here is the fix for that issue. Have you found any good strategies yet? Don't forget me when you are rich!
